const b = 5;
const a = 10;
const c = a + b;
console.log(c);
const k = 15;
const l = 20;
const s = 25;
const d = k + l + s;
console.log(d);
const t = "Hello";
const u = "World";
const v = t + u;
const w = "Hello";
const x = "World";
const y = w + x;
console.log(y);
